environment:
  matrix:
    - nodejs_version: 6.2
    # Note: --inspect crashes in .4 and .5, and in x64 before 6.8. https://github.com/nodejs/node/issues/8155
    - nodejs_version: 6.11
    - nodejs_version: 7.10
    - nodejs_version: 8.10
    - nodejs_version: 9.9

matrix:
  allow_failures:
    - nodejs_version: 6.2

install:
  - ps: >
      if ($env:nodejs_version -eq 6.2) {
        Install-Product node $env:nodejs_version x64
        npm i -g node-nightly
        node-nightly
      } else {
        Install-Product node $env:nodejs_version x64
      }

build_script:
  - npm install
  - npm run build

test_script:
  - npm test
  - npm run package